using BenMcLean.Wolf3D.Assets;
using BenMcLean.Wolf3D.Assets.Graphics;
using BenMcLean.Wolf3D.Shared;
using BenMcLean.Wolf3D.VR.VR;
using Godot;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;

namespace BenMcLean.Wolf3D.VR;

/// <summary>
/// Manages VR-specific 3D rendering assets.
/// Converts VSwap wall and sprite textures into Godot 3D materials optimized for VR.
/// Loads once at game start and persists until program termination.
/// </summary>
public static class VRAssetManager
{
	/// <summary>
	/// Scale factor for upscaling textures. Default is 1x (native 64x64).
	/// 4x gives 256x256, 8x gives 512x512, 16x gives 1024x1024.
	/// </summary>
	public static byte ScaleFactor { get; private set; } = 1;
	/// <summary>
	/// Opaque materials (used for walls and normal door quads), indexed by VSwap page number.
	/// </summary>
	public static IReadOnlyDictionary<ushort, ShaderMaterial> OpaqueMaterials { get; private set; }
	/// <summary>
	/// Sprite materials for billboarded objects, indexed by VSwap page number.
	/// </summary>
	public static IReadOnlyDictionary<ushort, ShaderMaterial> SpriteMaterials { get; private set; }
	/// <summary>
	/// Sprite textures for billboarded objects, indexed by VSwap page number.
	/// </summary>
	public static IReadOnlyDictionary<ushort, Texture2D> SpriteTextures { get; private set; }
	/// <summary>
	/// Voxel atlas loaded from res://Resources/VOXELS.W3D.
	/// Contains 3D model geometry for VR weapons
	/// </summary>
	public static VoxelAtlas VoxelAtlas { get; private set; }
	/// <summary>
	/// True when the current game's XML explicitly enables voxel weapons.
	/// Controls whether the runtime is allowed to offer/use voxel weapons at all.
	/// </summary>
	public static bool HasVoxelWeapons { get; private set; }
	/// <summary>
	/// Crosshair texture (13x11 pixels, white on transparent background).
	/// </summary>
	public static ImageTexture CrosshairTexture { get; private set; }
	/// <summary>
	/// Crosshair material for the aim indicator quad.
	/// </summary>
	public static StandardMaterial3D CrosshairMaterial { get; private set; }
	/// <summary>
	/// Cache of flipped opaque materials with horizontally mirrored UVs.
	/// Only contains materials for door textures. Used with negative scale for correct handle orientation.
	/// </summary>
	private static Dictionary<ushort, ShaderMaterial> _flippedOpaqueMaterials;
	/// <summary>
	/// Shared GLSL function implementing rotated-grid 4-tap supersampling (RGSS) with a mip LOD bias,
	/// per bgolus "Sharper Mipmapping using Shader-Based Supersampling". Reused verbatim across the
	/// opaque, sprite, and flipped-door shaders below (and the floor/ceiling tiling shader in Walls.cs,
	/// for Super 3D Noah's Ark's textured floors/ceilings) so the sampling logic exists in one place,
	/// even though it's textually inlined into each shader's source (this project inlines shader code
	/// in C# rather than using separate .gdshader files, so there's no #include mechanism to share it
	/// with). Reuses the mip chain VRAssetManager already generates via Image.GenerateMipmaps() - no
	/// extra VRAM cost. Guards against supersampling at native resolution/magnification (via the
	/// texture-space derivative magnitude) so close-up pixel art stays exactly as sharp as plain
	/// nearest sampling.
	/// </summary>
	internal static readonly string RgssSampleFunction = $@"
vec4 rgss_sample(sampler2D tex, vec2 uv) {{
	vec2 texSize = vec2(textureSize(tex, 0));
	vec2 dx = dFdx(uv);
	vec2 dy = dFdy(uv);
	// Disable supersampling when at native resolution or magnified, so close-up pixel art stays sharp.
	float guard = clamp(0.5 * log2(max(dot(dx * texSize, dx * texSize), dot(dy * texSize, dy * texSize))), 0.0, 1.0);
	dx *= guard;
	dy *= guard;
	vec4 c = vec4(0.0);
	c += texture(tex, uv + 0.125 * dx + 0.375 * dy, {Constants.MipBias});
	c += texture(tex, uv - 0.125 * dx - 0.375 * dy, {Constants.MipBias});
	c += texture(tex, uv + 0.375 * dx - 0.125 * dy, {Constants.MipBias});
	c += texture(tex, uv - 0.375 * dx + 0.125 * dy, {Constants.MipBias});
	return c * 0.25;
}}
";
	/// <summary>
	/// Shared shader for opaque wall/door quads (normal, unflipped UVs).
	/// filter_nearest_mipmap (not plain filter_nearest) is required so the mip chain generated by
	/// GenerateMipmaps() is actually used - plain nearest filtering always samples mip 0 regardless
	/// of distance, which is what caused distant walls to shimmer before this change.
	/// </summary>
	private static readonly Shader _opaqueShader = new() { Code = @"
shader_type spatial;
render_mode unshaded, cull_back;

uniform sampler2D albedo_texture : source_color, filter_nearest_mipmap, repeat_disable;
" + RgssSampleFunction + @"
void fragment() {
	ALBEDO = rgss_sample(albedo_texture, UV).rgb;
}
", };
	/// <summary>
	/// Shared shader for flipped door materials with horizontal UV flipping.
	/// Uses back-face culling (same as normal quads) - the negative scale makes it face the opposite direction.
	/// UV flip compensates for the geometry flip to keep door handles on the correct side.
	/// </summary>
	private static readonly Shader _flippedDoorShader = new() { Code = @"
shader_type spatial;
render_mode unshaded, cull_back;

uniform sampler2D albedo_texture : source_color, filter_nearest_mipmap, repeat_disable;
" + RgssSampleFunction + @"
void fragment() {
	vec2 uv = vec2(1.0 - UV.x, UV.y);//Flip UVs horizontally to compensate for geometry flip
	ALBEDO = rgss_sample(albedo_texture, uv).rgb;//Don't set ALPHA - doors are opaque and shouldn't use alpha blending
}
", };
	/// <summary>
	/// Shared shader for opaque billboard sprites (raw Spear tile art pages before SpritePage).
	/// Mirrors the previous StandardMaterial3D settings: Transparency Disabled, CullMode Back,
	/// DepthDrawMode Always.
	/// </summary>
	private static readonly Shader _spriteOpaqueShader = new() { Code = @"
shader_type spatial;
render_mode unshaded, cull_back, depth_draw_always;

uniform sampler2D albedo_texture : source_color, filter_nearest_mipmap, repeat_disable;
" + RgssSampleFunction + @"
void fragment() {
	ALBEDO = rgss_sample(albedo_texture, UV).rgb;
}
", };
	/// <summary>
	/// Shared shader for true sprite pages (binary alpha cutout billboards).
	/// Mirrors the previous StandardMaterial3D settings: Transparency AlphaScissor (threshold 0.5),
	/// CullMode Back, DepthDrawMode Always.
	/// </summary>
	private static readonly Shader _spriteScissorShader = new() { Code = @"
shader_type spatial;
render_mode unshaded, cull_back, depth_draw_always;

uniform sampler2D albedo_texture : source_color, filter_nearest_mipmap, repeat_disable;
" + RgssSampleFunction + @"
void fragment() {
	vec4 c = rgss_sample(albedo_texture, UV);
	ALBEDO = c.rgb;
	ALPHA = c.a;
	ALPHA_SCISSOR_THRESHOLD = 0.5;
}
", };
	/// <summary>
	/// Reference to the VSwap being used (from SharedAssetManager).
	/// </summary>
	private static VSwap _vswap;
	/// <summary>
	/// Initializes VR assets from the currently loaded game.
	/// Eagerly converts all wall and sprite textures to 3D materials.
	/// Should be called once after SharedAssetManager.LoadGame().
	/// </summary>
	/// <param name="scaleFactor">Upscaling factor (default 1x for native 64x64 textures)</param>
	public static void Initialize(byte scaleFactor = 1)
	{
		// Get VSwap from SharedAssetManager
		_vswap = Shared.SharedAssetManager.CurrentGame?.VSwap
			?? throw new InvalidOperationException("SharedAssetManager.CurrentGame.VSwap is null. Load a game first.");
		ScaleFactor = scaleFactor;
		_flippedOpaqueMaterials = [];
		HasVoxelWeapons = bool.TryParse(
			Shared.SharedAssetManager.CurrentGame.XML
				.Element("VSwap")?.Attribute("VoxelWeapons")?.Value,
			out bool xmlVoxelWeapons)
			&& xmlVoxelWeapons;
		if (HasVoxelWeapons)
			using (Stream stream = typeof(VRAssetManager).Assembly.GetManifestResourceStream("BenMcLean.Wolf3D.VR.Resources.VOXELS.W3D")
				?? throw new InvalidOperationException("Embedded resource VOXELS.W3D not found in assembly."))
				VoxelAtlas = new VoxelAtlas(stream, _vswap.SpritesByName);
		else
			VoxelAtlas = null;
		// Create crosshair texture (13x11 pixels, white on transparent background)
		byte[] crosshairData = new byte[13 * 11 * 4]; // RGBA8888, all transparent
		crosshairData = crosshairData.DrawCrosshair(width: 13);
		Image crosshairImage = Image.CreateFromData(13, 11, false, Image.Format.Rgba8, crosshairData);
		CrosshairTexture = ImageTexture.CreateFromImage(crosshairImage);
		CrosshairMaterial = new StandardMaterial3D
		{
			AlbedoTexture = CrosshairTexture,
			Transparency = BaseMaterial3D.TransparencyEnum.AlphaScissor,
			AlphaScissorThreshold = 0.5f,
			TextureFilter = BaseMaterial3D.TextureFilterEnum.Nearest,
			ShadingMode = BaseMaterial3D.ShadingModeEnum.Unshaded,
			CullMode = BaseMaterial3D.CullModeEnum.Disabled, // Visible from both sides
		};
		// Eagerly convert all opaque materials (walls and doors) using parallelization
		// Only process pages that actually exist in the VSwap (skip null entries)
		OpaqueMaterials = Enumerable.Range(0, _vswap.SpritePage)
			.Where(pageNumber => _vswap.Pages[pageNumber] is not null)
			.Parallelize(pageNumber => new KeyValuePair<ushort, ShaderMaterial>((ushort)pageNumber, CreateOpaqueMaterial((ushort)pageNumber)))
			.ToDictionary();
		// Eagerly convert all billboard textures using parallelization.
		// Spear of Destiny stores some static object art on pages before SpritePage. Those
		// pages are raw 64x64 tiles, not masked RLE sprites, so billboard rendering must
		// reuse the already-correct opaque textures for them instead of reprocessing them as
		// sprite pages.
		SpriteTextures = Enumerable.Range(0, _vswap.Pages.Length)
			.Where(pageNumber => _vswap.Pages[pageNumber] is not null)
			.Parallelize(pageNumber => new KeyValuePair<ushort, Texture2D>((ushort)pageNumber, CreateBillboardTexture((ushort)pageNumber)))
			.Where(kvp => kvp.Value is not null)
			.ToDictionary();
		// Eagerly convert all sprite materials from the pre-created textures
		SpriteMaterials = SpriteTextures
			.Parallelize(kvp => new KeyValuePair<ushort, ShaderMaterial>(kvp.Key, CreateSpriteMaterial(kvp.Key, kvp.Value)))
			.ToDictionary();
	}
	/// <summary>
	/// Creates a ShaderMaterial for a billboard sprite from an already-created (upscaled, mipmapped) texture.
	/// Pages before SpritePage are raw tile art used as opaque billboards in Spear (no alpha handling);
	/// real sprite pages use alpha scissor for binary transparency like original Wolf3D.
	/// </summary>
	private static ShaderMaterial CreateSpriteMaterial(ushort pageNumber, Texture2D texture)
	{
		ShaderMaterial material = new()
		{
			Shader = pageNumber < _vswap.SpritePage ? _spriteOpaqueShader : _spriteScissorShader,
		};
		material.SetShaderParameter("albedo_texture", texture);
		return material;
	}
	/// <summary>
	/// Creates a billboard texture for a VSwap page.
	/// Pages before SpritePage are raw wall/tile art and reuse the opaque texture; pages at or
	/// after SpritePage are true sprite pages and need their own texture creation path.
	/// </summary>
	private static Texture2D CreateBillboardTexture(ushort pageNumber) =>
		pageNumber < _vswap.SpritePage
			? OpaqueMaterials.TryGetValue(pageNumber, out ShaderMaterial material)
				? material.GetShaderParameter("albedo_texture").As<Texture2D>()
				: null
			: CreateSpriteTexture(pageNumber);
	/// <summary>
	/// Eagerly creates flipped materials for the specified door texture indices.
	/// Returns a dictionary of the created materials indexed by texture page number.
	/// </summary>
	public static Dictionary<ushort, ShaderMaterial> CreateFlippedMaterialsForDoors(IEnumerable<ushort> doorTextureIndices)
	{
		Dictionary<ushort, ShaderMaterial> materials = [];
		foreach (ushort pageNumber in doorTextureIndices.Distinct())
		{
			ShaderMaterial material = CreateFlippedMaterial(pageNumber);
			materials[pageNumber] = material;
			_flippedOpaqueMaterials[pageNumber] = material; // Cache for future reference
		}
		return materials;
	}
	/// <summary>
	/// Creates a ShaderMaterial for an opaque texture (walls and doors) with VR-optimized settings.
	/// Applies upscaling, generates mipmaps, and uses RGSS supersampling for sharp-up-close,
	/// shimmer-free-at-distance rendering.
	/// </summary>
	private static ShaderMaterial CreateOpaqueMaterial(ushort pageNumber)
	{
		// Get the original texture data from VSwap (will throw if page doesn't exist)
		byte[] originalData = _vswap.Pages[pageNumber],
			// Upscale the texture data
			scaledData = originalData.Upscale(ScaleFactor, ScaleFactor, _vswap.TileSqrt);
		int scaledSize = _vswap.TileSqrt * ScaleFactor,
			// Debug: Check data validity
			expectedSize = scaledSize * scaledSize * 4; // RGBA = 4 bytes per pixel
		if (scaledData.Length != expectedSize)
		{
			GD.PrintErr($"ERROR: Page {pageNumber} has wrong data size: {scaledData.Length} bytes, expected {expectedSize}");
			return new ShaderMaterial { Shader = _opaqueShader };
		}
		// Create Godot Image with mipmaps disabled initially
		Image image = Image.CreateFromData(
			width: scaledSize,
			height: scaledSize,
			useMipmaps: false, // Don't create mipmaps during construction
			format: Image.Format.Rgba8,
			data: scaledData);
		// Check if image was created successfully
		if (image is null)
		{
			GD.PrintErr($"ERROR: Image.CreateFromData returned null for page {pageNumber}");
			return new ShaderMaterial { Shader = _opaqueShader };
		}
		// Generate mipmaps after creation
		image.GenerateMipmaps();
		// Create ImageTexture from the image
		ImageTexture texture = ImageTexture.CreateFromImage(image);
		// Debug: Verify texture was created
		if (texture is null)
		{
			GD.PrintErr($"ERROR: ImageTexture.CreateFromImage returned null for page {pageNumber}, image size: {image.GetSize()}");
			return new ShaderMaterial { Shader = _opaqueShader };
		}
		// Create material with VR-optimized settings (RGSS supersampling, sharp up close, no shimmer at distance)
		ShaderMaterial material = new() { Shader = _opaqueShader };
		material.SetShaderParameter("albedo_texture", texture);
		return material;
	}
	/// <summary>
	/// Creates a ShaderMaterial with horizontally flipped/mirrored UVs.
	/// Used for flipped door quads combined with negative scale geometry.
	/// UV flip compensates for the geometry flip to ensure door handles appear on the correct side.
	/// </summary>
	private static ShaderMaterial CreateFlippedMaterial(ushort pageNumber)
	{
		// Get the original texture data from VSwap (will throw if page doesn't exist)
		byte[] originalData = _vswap.Pages[pageNumber],
			// Upscale the texture data
			scaledData = originalData.Upscale(ScaleFactor, ScaleFactor, _vswap.TileSqrt);
		int scaledSize = _vswap.TileSqrt * ScaleFactor;
		// Create Godot Image
		Image image = Image.CreateFromData(
			width: scaledSize,
			height: scaledSize,
			useMipmaps: false,
			format: Image.Format.Rgba8,
			data: scaledData);
		if (image is null)
			return null;
		// Generate mipmaps
		image.GenerateMipmaps();
		// Create ImageTexture from the image
		ImageTexture texture = ImageTexture.CreateFromImage(image);
		if (texture is null)
			return null;
		// Create shader material with back-face culling and UV flipping
		ShaderMaterial material = new()
		{
			Shader = _flippedDoorShader,
		};
		// Set the texture uniform
		material.SetShaderParameter("albedo_texture", texture);
		return material;
	}
	/// <summary>
	/// Creates a Texture2D for a sprite page. Applies upscaling and generates mipmaps.
	/// Returns null and logs an error if creation fails.
	/// </summary>
	private static ImageTexture CreateSpriteTexture(ushort pageNumber)
	{
		// Get the original texture data from VSwap (will throw if page doesn't exist)
		byte[] originalData = _vswap.Pages[pageNumber],
			// Upscale the texture data
			scaledData = originalData.Upscale(ScaleFactor, ScaleFactor, _vswap.TileSqrt);
		int scaledSize = _vswap.TileSqrt * ScaleFactor;
		// Create Godot Image with mipmaps disabled initially
		Image image = Image.CreateFromData(
			width: scaledSize,
			height: scaledSize,
			useMipmaps: false,
			format: Image.Format.Rgba8,
			data: scaledData);
		if (image is null)
		{
			GD.PrintErr($"ERROR: Image.CreateFromData returned null for sprite page {pageNumber}");
			return null;
		}
		// Generate mipmaps after creation
		image.GenerateMipmaps();
		// Create ImageTexture from the image
		ImageTexture texture = ImageTexture.CreateFromImage(image);
		if (texture is null)
			GD.PrintErr($"ERROR: ImageTexture.CreateFromImage returned null for sprite page {pageNumber}");
		return texture;
	}
	/// <summary>
	/// Disposes all loaded VR assets.
	/// Currently not needed as VR assets persist until program termination,
	/// but included for completeness.
	/// </summary>
	public static void Cleanup()
	{
		// Dispose opaque materials
		if (OpaqueMaterials is not null)
			foreach (ShaderMaterial material in OpaqueMaterials.Values)
				material?.Dispose();
		// Dispose sprite materials
		if (SpriteMaterials is not null)
			foreach (ShaderMaterial material in SpriteMaterials.Values)
				material?.Dispose();
		// Dispose sprite textures (after materials, which hold references to them)
		if (SpriteTextures is not null)
			foreach (Texture2D texture in SpriteTextures.Values)
				texture?.Dispose();
		// Dispose flipped materials
		if (_flippedOpaqueMaterials is not null)
			foreach (ShaderMaterial material in _flippedOpaqueMaterials.Values)
				material?.Dispose();
		_flippedOpaqueMaterials?.Clear();
		CrosshairMaterial?.Dispose();
		CrosshairMaterial = null;
		CrosshairTexture?.Dispose();
		CrosshairTexture = null;
		_vswap = null;
		VoxelAtlas?.Dispose();
		VoxelAtlas = null;
		HasVoxelWeapons = false;
	}
}
